# Generated by Django 2.2.3 on 2020-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=254, null=True, verbose_name='Full Name')),
                ('last_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
