export const ADD_MORE_BUTTON = 'ADD_MORE_BUTTON';
export const SUB_MORE_BUTTON = 'SUB_MORE_BUTTON';
export const REMOVE_CART_ITEM_BUTTON = 'REMOVE_CART_ITEM_BUTTON';
export const REDUCE_CART_ITEM = 'REDUCE_CART_ITEM';
export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';