# Generated by Django 2.2.3 on 2020-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
